#环境表
CREATE TABLE `tg_antnet_env` (
  `id` BIGINT(20) NOT NULL DEFAULT '0' COMMENT '环境ID',
  `env_name` VARCHAR(255) DEFAULT '' COMMENT '环境名称',
  `m_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  `c_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT '环境表';

#应用表
CREATE TABLE `tg_antnet_app`(
  `id` BIGINT(20) NOT NULL DEFAULT '0' COMMENT '应用ID',
  `sys_name` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '系统名称',
  `model_name` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '模块名称',
  `m_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  `c_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT '应用表';

#配置表
CREATE TABLE `tg_antnet_config` (
  `id` BIGINT(20) NOT NULL DEFAULT '0' COMMENT '配置ID',
  `env_id` BIGINT(20) NOT NULL DEFAULT '0' COMMENT '环境ID',
  `app_id` BIGINT(20) NOT NULL DEFAULT '0' COMMENT '应用ID',
  `adapter_version` VARCHAR(255) NOT NULL DEFAULT '0' COMMENT '适用版本',
  `status` TINYINT(4) NOT NULL DEFAULT '0' COMMENT '0 生效，1 失效',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT '应用表';